AZURE_LOCATION: 'westus2'
RESOURCE_NAME_PREFIX: 'LanZone'
ENVIRONMENT_TAG: 'prod'
DEPLOYMENT_NAME: 'deployment-azl'
VM_USERNAME: 'VMazl'
ACCOUNT_NAME: 'github.com/javprod'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'
